default_agent: sec307_agent
agents:
  sec307_agent:
    name: sec307_agent
    language: python
    node_version: '20'
    entrypoint: /workshop/static/AgentCode/agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /workshop/static/AgentCode
    aws:
      execution_role: arn:aws:iam::385665588806:role/sec307-agent-identity-agentruntime-execution-role
      execution_role_auto_create: false
      account: '385665588806'
      region: us-east-1
      ecr_repository: 385665588806.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-sec307_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: sec307_agent-KEIQdH7R6I
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:385665588806:runtime/sec307_agent-KEIQdH7R6I
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-sec307_agent-builder
      execution_role: arn:aws:iam::385665588806:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-2b16e33806
      source_bucket: bedrock-agentcore-codebuild-sources-385665588806-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_bdPW9I2B8/.well-known/openid-configuration
        allowedClients:
        - 845jckmktnfrb58s05iblc50l
    request_header_configuration:
      requestHeaderAllowlist:
      - Authorization
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
